In [15]:
def return_even(lst):
    new_lst = []
    for i in lst:
        if i%2 == 0:
            new_lst.append(i)
    return new_lst


In [18]:
return_even([1, 2, 4])

[2, 4]

In [20]:
def return_m5(lst):
    new_lst = []
    for i in lst:
        if i>5:
            new_lst.append(i)
    return new_lst

In [44]:
g = lambda n: n%2==0
print(g(5))

False


In [46]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
filter_list = list(filter(lambda x: x%3!=0, lst))
print(filter_list)

[1, 2, 4, 5, 7, 8]


In [24]:
return_m5([1, 2, 4, 5, 6, 7])

[6, 7]

In [53]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
map_list = list(map(lambda x: '$'+str(round(x*1.07, 2)), lst))
print(map_list)

['$1.07', '$2.14', '$3.21', '$4.28', '$5.35', '$6.42', '$7.49', '$8.56']


In [57]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
map_list = list(map(lambda x: f'${round(x*1.07, 2)}', lst))
print(map_list)

['$1.07', '$2.14', '$3.21', '$4.28', '$5.35', '$6.42', '$7.49', '$8.56']


In [62]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
map_list = list(map(lambda x: f'${round(x*1.07, 2) if x>5 else x}', lst))
print(map_list)

['$1', '$2', '$3', '$4', '$5', '$6.42', '$7.49', '$8.56']


In [63]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
filter_list = list(map(lambda x: x**2 if x>5 else x, lst))
print(filter_list)

[1, 2, 3, 4, 5, 36, 49, 64]


In [75]:
from functools import reduce
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
filter_list = reduce(lambda x, s: x + s , lst)
print(filter_list)

55


In [77]:
import numpy as np 

In [80]:
l1 = [1, 2, 3, 4, 5]
r1 = np.array(l1)
print(r1)
print(r1.shape)
print(r1[0])
print(r1[1])

[1 2 3 4 5]
(5,)
1
2


In [95]:
l2 = [6, 7, 8, 9, 0]
r2 = np.array([l1, l2])
print(r2)
print(r2.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)


In [104]:
l2_e = [6, 7, 8,  0]
r2_e = np.array([l1, l2_e])
print(r2_e)
print(r2_e.shape)
print(r2_e[0])

[list([1, 2, 3, 4, 5]) list([6, 7, 8, 0])]
(2,)
[1, 2, 3, 4, 5]


In [99]:
n=[4, 3, 2, 1, 0]
print(r1[n])

[5 4 3 2 1]


In [105]:
n=[4, 3, 2, 1, 0]
print(r2[0, n])

[5 4 3 2 1]


In [109]:
a1 = np.zeros(2)
print(a1.shape)

(2,)


In [117]:
a1 = np.full([2, 3], 4)
print(a1)

[[4 4 4]
 [4 4 4]]


In [127]:
a6=np.arange(10)
print(a6)

[0 1 2 3 4 5 6 7 8 9]


In [133]:
a7 = np.array([[1, 2, 3, 4, 5],
              [4, 5, 6, 7, 8], 
              [9, 8, 7, 6, 5]])
print(a7)
b1 = a7[1:3, :3]
print(b1)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
[[4 5 6]
 [9 8 7]]


In [143]:
b1 = a7[a7.shape[0]-1:a7.shape[0]+6 ]
print(b1)

[[9 8 7 6 5]]


In [147]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [168]:
a8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
even_a8 = (a8 % 2 ==0)
print(even_a8)
print(a8[even_a8])
print(a8[a8>5])

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]
[6 7 8 9]


In [170]:
l1 = [1, True, "ok"]
a9 = np.array(l1)
print(a9)

['1' 'True' 'ok']


In [175]:
l1 = [1,True, False, 1.0]
a9 = np.array(l1)
print(a9)

[1. 1. 0. 1.]


In [195]:
x1 = np.array([[1, 2, 3], [4, 5, 6]])
y1 = np.array([[7, 8, 9], [2, 3, 4]])
print(x1 + y1)

print(x1 - y1)

print(x1*y1)

print(np.dot(x1, y1.T))

print(x1.cumsum())

z1 = np.array([x1, y1])
print(z1)
print(z1.cumsum(axis=0))
print(z1.cumsum(axis=1))
print(z1.cumsum(axis=2))

[[ 8 10 12]
 [ 6  8 10]]
[[-6 -6 -6]
 [ 2  2  2]]
[[ 7 16 27]
 [ 8 15 24]]
[[ 50  20]
 [122  47]]
[ 1  3  6 10 15 21]
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 3 4]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8 10 12]
  [ 6  8 10]]]
[[[ 1  2  3]
  [ 5  7  9]]

 [[ 7  8  9]
  [ 9 11 13]]]
[[[ 1  3  6]
  [ 4  9 15]]

 [[ 7 15 24]
  [ 2  5  9]]]


In [247]:
persons = np.array(['Johnny', 'Mary', 'Peter', 'Will', 'Joe'])
ages = np.array([34, 12, 37, 5, 13])
heights = np.array([1.76, 1.2, 1.68, 0.5, 1.25])
print('---Before Sorting ---')
comb = np.array([persons, ages, heights])


sorted_name = np.argsort(persons)
print(persons[sorted_name])
print(ages[sorted_name])
print(heights[sorted_name])


# use zip and lambda function to combine into tuple 



zip_comb = zip(persons, ages, heights)

print(tuple(zip_comb))

comb_sort_by_name = np.argsort([zip_comb[0, :]], axis = 1)

# print(comb)
# comb_sort_by_name = np.argsort([comb[0, :]], axis = 1)

# comb_sort_by_age = np.argsort([comb[1, :]], axis = 1)

# comb_sort_all_row = np.argsort(comb, axis = 1)

# print("")
# print("Sort by Name (ascending)--- ")
# print(np.take_along_axis(comb, comb_sort_by_name, axis=1) )

# print("")
# print("Sort by Name (descending)--- ")
# print(np.take_along_axis(comb, np.flip(comb_sort_by_name), axis=1))

# print("")
# print("Sort by Age (ascending)--- ")
# print(np.take_along_axis(comb, comb_sort_by_age, axis=1) )

# print("")
# print("Sort by Age (descending)--- ")
# print(np.take_along_axis(comb, np.flip(comb_sort_by_age), axis=1))

# print("")
# print("Sort in individual row --- ")
# print( np.take_along_axis(comb, comb_sort_all_row, axis=1) )

---Before Sorting ---
['Joe' 'Johnny' 'Mary' 'Peter' 'Will']
[13 34 12 37  5]
[1.25 1.76 1.2  1.68 0.5 ]
(('Johnny', 34, 1.76), ('Mary', 12, 1.2), ('Peter', 37, 1.68), ('Will', 5, 0.5), ('Joe', 13, 1.25))


TypeError: 'zip' object is not subscriptable

In [215]:
np.argsort([comb[0,:]], axis = 1)

array([[4, 0, 1, 2, 3]], dtype=int64)

In [242]:
names = np.array(['Ann', 'Joe', 'Mark'])
heights = np.array([1.5, 1.78, 1.6])
weights = np.array([65, 46, 59])

bmi = weights/heights**2
print(bmi)

print("Overweight: ", names[bmi>25])
print("Underweight: ", names[bmi<18.5])
print("Healthy: ", names[(bmi>=18.5) & (bmi<=25)])

[28.88888889 14.51836889 23.046875  ]
Overweight:  ['Ann']
Underweight:  ['Joe']
Healthy:  ['Mark']
